### ISSUE TITLE
Multi-root Workspace not supported?

### ISSUE THREAD

**Issue by beltaurus** [richterger/Perl-LanguageServer#21]
As soon as I try to work with multiple folders in my workspace, I'm getting the weirdest messages:

e.g.

![image](https://user-images.githubusercontent.com/54114043/81102360-61935080-8ec4-11ea-956a-0b2243d9fb9c.png)

or
![image](https://user-images.githubusercontent.com/54114043/81102254-3872c000-8ec4-11ea-9356-b8459370adf7.png)

Before I turn this into a test case, is the "Perl" VS Code Extension multi-root enabled?

**Comment by richterger** [comment]
Yes, multi root is supported and I personaly use it every day
Please set Log Level to 1 and post the first request from the output tab, which should show your workspaceFolders

**Comment by beltaurus** [comment]
I just upgraded both the extension and the Perl::LanguageServer to the latest (on my Linux machine).
When the Language server now starts, I'm getting the following error:
```
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x25d7b38), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
state_dir = /p/psg/flows/sw/regutils/21.1/1/linux64/framework/.vscode/perl-lang
Cannot make /.../.vscode (Permission denied) at /nfs/site/home/dseynhae/perl5/lib/perl5/Perl/LanguageServer/Workspace.pm line 127.
```

Some of my workspace folders are read-only (they contain corporate libraries)...
The language server is trying to create a folder in there...

The workspace folders are there, because I want to included them in my workspace search....

**Comment by beltaurus** [comment]
More status: For multi-root situations on Linux, the LS parses the files, and then closes the connection... After 5 restarts, LS won't work anymore...
Here is the last part of the output, when LS no longer wants to restart:
```
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x25be120), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
state_dir = /p/psg/data/dseynhae/overlays/regutils/framework/.vscode/perl-lang
loaded 100 files, parsed  files, 100 files
[Info  - 10:37:24 PM] Connection to server got closed. Server will restart.
[Error - 10:37:24 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/nfs/tor/disks/swuser_work_dseynhae/home/_vscode/extensions/richterger.perl-2.1.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
tcp server start listen on port 13603
tcp_bind: Address already in use at /nfs/site/home/dseynhae/perl5/lib/perl5/Perl/LanguageServer.pm line 418.
LS: apply_all_roles (Perl::LanguageServer=HASH(0x1405120), Perl::LanguageServer::Methods, Perl/LanguageServer/Methods.pm)
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::1=HASH(0x1405120), Perl::LanguageServer::Methods::workspace, Perl/LanguageServer/Methods/workspace.pm)
perlcmd = "/nfs/site/disks/psg_ctools_1/perl/5.24.1/linux64/rhel/bin/perl"
path_map = undef
perlinc = [
  "/nfs/site/home/dseynhae/perl5/lib/perl5",
  "\${workspaceFolder:regtest}/hld/util",
  "\${workspaceFolder:regtest}/hld/opencl/util",
]
file_filter_regex = "(?:\\.pm|\\.pl)\$"
ignore_dir = { ".git" => 1, ".svn" => 1, ".vscode" => 1 }
background_parser folders = {
  "file:///p/psg/data/dseynhae/overlays/regutils/bin"         => "/p/psg/data/dseynhae/overlays/regutils/bin",
  "file:///p/psg/data/dseynhae/overlays/regutils/framework"   => "/p/psg/data/dseynhae/overlays/regutils/framework",
  "file:///p/psg/swip/w/dseynhae/dev/linux64/main/p4/regtest" => "/p/psg/swip/w/dseynhae/dev/linux64/main/p4/regtest",
}
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x1405120), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
state_dir = /p/psg/data/dseynhae/overlays/regutils/framework/.vscode/perl-lang
loaded 100 files, parsed  files, 100 files

```

**Comment by richterger** [comment]
Regarding the issue with ReadOnly Workspace: The LanguageServer tries to create a cache directory in the .vscode directory underneath the Wokrspace Folder which is passed as rootUri, which is normaly the first directoy you have used to create the workspace. As long as this first directory is writable it should work.

Regarding the other issue: The relevant message is "tcp_bind: Address already in use". There is already a LanguageServer running. Please kill it manualy, afterwards reload the window of vscode

**Comment by beltaurus** [comment]
Good tip... I will start making a "_CONFIG_ directory the defacto first folder in my workspace...
