### ISSUE TITLE
Perl Language server is crashing in Windows 10 OS + Strawberry Perl , weird directories are created

### ISSUE THREAD

**Issue by bakkiaraj** [richterger/Perl-LanguageServer#34]
Versions
----------
OS: Windows 10
VScode: 1.46.1
Perl Language Server extension: 2.1.0
Perl : This is perl 5, version 22, subversion 3 (v5.22.3) built for MSWin32-x64-multi-thread

Issue 
------
The language server simply dont work. There is "E:\e%3A\Eclipse_WorkSpace\PerlExamples\Networking\test\.vscode\perl-lang\e%3A\Eclipse_WorkSpace\PerlExamples\Networking\test" dir created in E:\ !!!

Here is the crash report

tcp server start listen on port 8796
tcp_bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. at C:/tools/Strawberry/perl/site/lib/Perl/LanguageServer.pm line 418.
LS: apply_all_roles (Perl::LanguageServer=HASH(0x46cddf0), Perl::LanguageServer::Methods, Perl/LanguageServer/Methods.pm)
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::1=HASH(0x46cddf0), Perl::LanguageServer::Methods::workspace, Perl/LanguageServer/Methods/workspace.pm)
perlcmd = "C:\\tools\\Strawberry\\perl\\bin\\perl.exe"
path_map = undef
perlinc = undef
file_filter_regex = "(?:\\.pm|\\.pl)\$"
ignore_dir = { ".git" => 1, ".svn" => 1, ".vscode" => 1 }
background_parser folders = {
  "file:///e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test" => "/e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test",
}
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x46cddf0), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
initial parsing done, loaded  files, parsed  files, 0 files
[Info  - 8:26:27 pm] Connection to server got closed. Server will restart.
[Error - 8:26:27 pm] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at LanguageClient.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-languageclient\lib\client.js:2309:42)
	at LanguageClient.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-languageclient\lib\main.js:155:15)
	at closeHandler (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-languageclient\lib\client.js:2296:18)
	at CallbackList.invoke (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\main.js:240:26)
	at CallbackList.invoke (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\<user>\.vscode\extensions\richterger.perl-2.1.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
tcp server start listen on port 8796
tcp_bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. at C:/tools/Strawberry/perl/site/lib/Perl/LanguageServer.pm line 418.
LS: apply_all_roles (Perl::LanguageServer=HASH(0x4669928), Perl::LanguageServer::Methods, Perl/LanguageServer/Methods.pm)
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::1=HASH(0x4669928), Perl::LanguageServer::Methods::workspace, Perl/LanguageServer/Methods/workspace.pm)
perlcmd = "C:\\tools\\Strawberry\\perl\\bin\\perl.exe"
path_map = undef
perlinc = undef
file_filter_regex = "(?:\\.pm|\\.pl)\$"
ignore_dir = { ".git" => 1, ".svn" => 1, ".vscode" => 1 }
background_parser folders = {
  "file:///e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test" => "/e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test",
}
LS: apply_all_roles (Moose::Meta::Class::__ANON__::SERIAL::2=HASH(0x4669928), Perl::LanguageServer::Methods::textDocument, Perl/LanguageServer/Methods/textDocument.pm)
initial parsing done, loaded  files, parsed  files, 0 files
parse /e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test/test.pl -> file:///e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test/test.pl
state_dir = /e%3A/Eclipse_WorkSpace/PerlExamples/Networking/test/.vscode/perl-lang

**Comment by rai-gaurav** [comment]
Maybe related to https://github.com/richterger/Perl-LanguageServer/issues/33.
See the know issue section on - https://marketplace.visualstudio.com/items?itemName=richterger.perl

**Comment by bakkiaraj** [comment]
I do not know , How I miss it from known issues list. Still, Windows OS is a main os @work , Any plan make it available for Windows OS?
